"""add investigator notes

Revision ID: 5ba7200e54a1
Revises: 009bc7874b40
Create Date: 2026-06-18 13:57:46.069281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba7200e54a1'
down_revision = '009bc7874b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigator_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('note_text', sa.Text(), nullable=True))
        batch_op.drop_column('filename')
        batch_op.drop_column('description')
        batch_op.drop_column('content_type')
        batch_op.drop_column('filepath')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('evidence_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('content_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('note_text')
        batch_op.drop_column('file_path')
        batch_op.drop_column('item_type')

    op.drop_table('investigator_notes')
    # ### end Alembic commands ###
