"""add channel field

Revision ID: 83ebb48e4a53
Revises: 3c3c0f2e9b11
Create Date: 2026-06-29 12:48:47.113565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ebb48e4a53'
down_revision = '3c3c0f2e9b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('display_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("nextval('cases_display_id_seq'::regclass)"))
        batch_op.create_unique_constraint(None, ['display_id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('channel')

    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('display_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("nextval('cases_display_id_seq'::regclass)"))

    # ### end Alembic commands ###
