from flask import send_file, jsonify
from flask_jwt_extended import jwt_required

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)
from reportlab.lib.styles import getSampleStyleSheet

from app.reports.report_generator import reports_bp
from app.models.case import Case
from app.models.verification import Verification
from app.models.supervisor_approval import SupervisorApproval
from app.intelligence.fir_readiness import calculate_fir_readiness
from app.ai.ollama_client import call_ollama as query_groq

import os


@reports_bp.route('/fir-draft/<case_id>', methods=['POST'])
@jwt_required()
def generate_fir_draft(case_id):
    from flask import request
    from werkzeug.security import check_password_hash
    from app.models.user import User
    from flask_jwt_extended import get_jwt_identity
    
    current_user_id = get_jwt_identity()
    user = User.query.get(current_user_id)
    
    data = request.get_json() or {}
    signature_password = data.get('signature_password')
    mock_details = data.get('mock_details', '')
    
    if not signature_password or not check_password_hash(user.password_hash, signature_password):
        return jsonify({"error": "Invalid digital signature"}), 401

    # --------------------------------------------------
    # Validate Case
    # --------------------------------------------------
    case = Case.query.get(case_id)

    if not case:
        return jsonify({
            "error": "Case not found"
        }), 404

    # --------------------------------------------------
    # Verification Status
    # --------------------------------------------------
    verification = Verification.query.filter_by(
        case_id=case_id
    ).first()

    verification_pct = (
        verification.completion_percentage
        if verification
        else 0.0
    )

    # --------------------------------------------------
    # Supervisor Approval
    # --------------------------------------------------
    approval = (
        SupervisorApproval.query
        .filter_by(case_id=case_id)
        .order_by(
            SupervisorApproval.requested_at.desc()
        )
        .first()
    )

    approval_status = (
        approval.status
        if approval
        else "none"
    )

    fir_text = f"""
FIRST INFORMATION REPORT (FIR)
Under Section 154 Cr.P.C.

Details provided by SIO:
{mock_details}

Generated by Fintelligence Platform.
"""

    # --------------------------------------------------
    # Create PDF
    # --------------------------------------------------
    from flask import current_app
    from app.models.evidence_item import EvidenceItem
    from app.extensions import db
    import time
    
    upload_folder = current_app.config.get('UPLOAD_FOLDER', 'uploads')
    evidence_dir = os.path.join(upload_folder, 'evidence', case_id)
    os.makedirs(evidence_dir, exist_ok=True)

    # Use a timestamp to prevent overwriting if multiple FIRs are generated
    timestamp = int(time.time())
    filename = f"fir_{case_id}_{timestamp}.pdf"
    pdf_path = os.path.join(evidence_dir, filename)

    styles = getSampleStyleSheet()

    doc = SimpleDocTemplate(pdf_path)

    story = []

    story.append(
        Paragraph(
            "FIRST INFORMATION REPORT",
            styles["Title"]
        )
    )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            f"<b>Case ID:</b> {case_id}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Risk Level:</b> {case.risk_level}",
            styles["Normal"]
        )
    )

    story.append(
        Paragraph(
            f"<b>Suspicion Score:</b> "
            f"{round(case.suspicion_score, 1)}",
            styles["Normal"]
        )
    )

    story.append(Spacer(1, 20))

    fir_paragraphs = fir_text.split("\n")

    for line in fir_paragraphs:

        if line.strip():

            story.append(
                Paragraph(
                    line,
                    styles["BodyText"]
                )
            )

            story.append(
                Spacer(1, 4)
            )

    doc.build(story)

    # Add EvidenceItem
    evidence = EvidenceItem(
        case_id=case_id,
        item_type="fir",
        file_path=pdf_path,
        uploaded_by=current_user_id,
        note_text="Automatically generated FIR Draft"
    )
    db.session.add(evidence)
    db.session.commit()

    # --------------------------------------------------
    # Return Downloadable PDF
    # --------------------------------------------------
    return send_file(
        pdf_path,
        as_attachment=True,
        download_name=filename,
        mimetype="application/pdf"
    )